apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - servicemonitor.yaml

helmCharts:
  - name: spark
    repo: https://charts.bitnami.com/bitnami
    version: 10.0.3
    releaseName: spark
    namespace: spark
    valuesFile: values.yaml
