apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

helmCharts:
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    version: 30.1.10
    releaseName: kafka
    namespace: kafka
    valuesFile: values.yaml
