apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
  - name: opensearch
    repo: https://opensearch-project.github.io/helm-charts
    version: 2.27.1
    releaseName: opensearch
    namespace: logging
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - credentials-secret.yaml
